services:
    cron.task.core.DeleteInactiveUsers:
        class: forumhulp\DeleteInactiveUsers\cron\task\core\delete_inactive_users
        arguments:
            - %core.root_path%
            - %core.php_ext%
            - @config
            - @dbal.conn
        calls:
            - [set_name, [cron.task.core.delete_inactive_users]]
        tags:
            - { name: cron.task }
    forumhulp.DeleteInactiveUsers.listener:
        class: forumhulp\DeleteInactiveUsers\event\listener
        arguments:
            - @controller.helper
        tags:
            - { name: event.listener }