services:
    cron.task.core.inactive_users:
        class: forumhulp\inactive_users\cron\task\core\inactive_users
        arguments:
            - %core.root_path%
            - %core.php_ext%
            - @config
            - @dbal.conn
        calls:
            - [set_name, [cron.task.core.inactive_users]]
        tags:
            - { name: cron.task }
    forumhulp.inactive_users.listener:
        class: forumhulp\inactive_users\event\listener
        arguments:
            - @controller.helper
        tags:
            - { name: event.listener }