services:
    forumhulp.cron.deleteinactiveusers:
        class: forumhulp\deleteinactiveusers\cron\task\core\delete_inactive_users
        arguments:
            - @user
            - @config
            - @config_text
            - @dbal.conn
            - @log
            - %core.root_path%
            - %core.php_ext%
        calls:
            - [set_name, [forumhulp.cron.delete_inactive_users]]
        tags:
            - { name: cron.task }
    forumhulp.deleteinactiveusers.listener:
        class: forumhulp\deleteinactiveusers\event\listener
        arguments:
            - @controller.helper
        tags:
            - { name: event.listener }